export const GET_ALL_CARS = "GET_ALL_CARS";
export const GET_CAR_DETAIL = "GET_CAR_DETAIL";
export const GET_ALL_COLORS = "GET_ALL_COLORS";
export const GET_ALL_MANUFACTURERS = "GET_ALL_MANUFACTURERS";

export const GET_ALL_CARS_SUCCESS = "GET_ALL_CARS_SUCCESS";
export const GET_CAR_DETAIL_SUCCESS = "GET_CAR_DETAIL_SUCCESS";
export const GET_ALL_COLORS_SUCCESS = "GET_ALL_COLORS_SUCCESS";
export const GET_ALL_MANUFACTURERS_SUCCESS = "GET_ALL_MANUFACTURERS_SUCCESS";

export const GET_ALL_CARS_ERROR = "GET_ALL_CARS_ERROR";
export const GET_CAR_DETAIL_ERROR = "GET_CAR_DETAIL_ERROR";
export const GET_ALL_COLORS_ERROR = "GET_ALL_COLORS_ERROR";
export const GET_ALL_MANUFACTURERS_ERROR = "GET_ALL_MANUFACTURERS_ERROR";

export const SORT_CARS = "SORT_CARS";
export const FILTER_CARS = "FILTER_CARS";

export const SORT_CARS_SUCCESS = "SORT_CARS_SUCCESS";
export const FILTER_CARS_SUCCESS = "FILTER_CARS_SUCCESS";

export const SORT_CARS_ERROR = "SORT_CARS_ERROR";
export const FILTER_CARS_ERROR = "FILTER_CARS_ERROR";

